import itertools
from collections import defaultdict
from typing import Mapping


def has_two(count: Mapping[str, int]) -> bool:
    """
    Returns True if a string has two of any letter
    """
    return any(value == 2 for value in count.values())


def has_three(count: Mapping[str, int]) -> bool:
    """
    Returns True if a string has two of any letter
    """
    return any(value == 3 for value in count.values())


def str_common(x: str, y: str) -> str:
    """
    Returns the parts of a string that are in common
    """
    return ''.join(a for a, b in zip(x, y) if a == b)


def letter_count(x: str) -> Mapping[str, int]:
    """
    Returns a mapping containing the count of each of the characters in a string
    """
    ret = defaultdict(int)
    for char in x:
        ret[char] += 1
    return ret


def part1(x: str) -> int:
    two_count, three_count = 0, 0
    for box_id in x.split():
        box_count = letter_count(box_id)
        if has_two(box_count):
            two_count += 1
        if has_three(box_count):
            three_count += 1
    return two_count * three_count


def part2(x: str) -> str:
    box_ids = x.split()
    for box1, box2 in itertools.combinations(box_ids, 2):
        common_parts = str_common(box1, box2)
        if len(box1) - len(common_parts) == 1:
            return common_parts


puzzle_input = '''
wxlnjevbfozadyiqpuzkrhstkg
wxlsjivbfodamyiqpuzcxhstkg
wxlnjevbfouammnqpuzcrhstkg
wxlnjevbfobwmyiqpuzprhstkg
wxlnjefbfodamyiqpuzcnustkg
wxlnjevbfodakyyupuzcrhstkg
wxlnjejbfodafynqpuzcrhstkg
wxlnjevbfodomyifptzcrhstkg
wxlnjevbfodamyiwcuzcrhstkz
wxlnjevbfofamyiqpuznrhstxg
wxlnjevbfodamyiqbupcrxstkg
wxjnjevbfodxmyeqpuzcrhstkg
xwlnjevbfosamyiqpuzcrhstkg
fxlnjevbfodrmyiqpuzcrbstkg
wxlnjevpfodamyiqquzzrhstkg
wwlnjenbfodawyiqpuzcrhstkg
wxrnjevbfodamyiqpuzlrhstrg
welnjeqbfodkmyiqpuzcrhstkg
walnjfvbfodamyiqpuzcrhwtkg
wdlnjevbfodamriqpuzjrhstkg
wxlnjevbfodmnyizpuzcrhstkg
wxlnjevbfodgmyiqpuxcrjstkg
wxlnjevbfkdamyiqpudcrestkg
wxlyjevbfodamyiqpuzcehstkj
wxlnjevamodamyiqpuzcrhatkg
fxlnqevsfodamyiqpuzcrhstkg
wqlnjevbfodanyiqvuzcrhstkg
wxlnjevbfoiamyzqpuzcrnstkg
wxlnjevbfodamyiqpuacrhsjig
wxlnjuvbfodzmyvqpuzcrhstkg
kxlnjevbfolamviqpuzcrhstkg
wxlnjesbfldamyiqpuycrhstkg
nxltjevbfodgmyiqpuzcrhstkg
ojlnjevbfooamyiqpuzcrhstkg
wxlnjevbfodaffiqpugcrhstkg
cxlnievbfodamyuqpuzcrhstkg
wxlouevbjodamyiqpuzcrhstkg
wafnjevbfhdamyiqpuzcrhstkg
wxlnjevbfxdamrpqpuzcrhstkg
wxlnjepffodamyiqphzcrhstkg
wxlnkevbfohamciqpuzcrhstkg
wzlnmevdfodamyiqpuzcrhstkg
wxlzjtvbfodamyiqpuzcrhstkd
gxlnjehbfojamyiqpuzcrhstkg
wxlnjeoqfodamyiqprzcrhstkg
nxllvevbfodamyiqpuzcrhstkg
wxlnjevtfomamyiqpurcrhstkg
sxlnjevafodamyikpuzcrhstkg
wxlnjevbfodamyfqpuzcyhztkg
wxlnjevbfodamyiqpulnrhstkh
wxlnwevbfodumyiqpuzqrhstkg
wxldjevbfodamyiqpzzcrhstkk
jxlnjevbfodamyiqphzcrnstkg
fxlnjeibfodcmyiqpuzcrhstkg
wxlnjevufodamyiqpnzcrhstkk
wglnjevbfodamyiqpuzcesstkg
wxlvjevbdodamyiqpuzcrhstkc
wxlnjevbfodabyicpuzcrhstkl
wxlnjevbfodamyiqpizcrhstvt
wolnjevbfodawyiqiuzcrhstkg
wxlyjevbfodamyuqpxzcrhstkg
wxlijevbfodamyikpuzyrhstkg
wxennevbfodamyiqpuzcrtstkg
wxlnjevbyodamyuqpwzcrhstkg
wxlnjevbfoiomyiqpuzcrhsteg
wxlnjehbrodamyiqpuicrhstkg
xxlnjevufodamyiqbuzcrhstkg
wxlojevbfodamyiqpezcrhatkg
wxljjevbfolamuiqpuzcrhstkg
wxlnjevbfodamyiqruzcrhstpi
wxlnjevbfomamyiqjnzcrhstkg
wxlnjevbfodahyiqzuzcrhstpg
wxtnjevbfodamyiqpuzcrhsdrg
wxlnjevbfodamynrpuzcrhstkz
wxlqjevefqdamyiqpuzcrhstkg
wxlnjevbfmdamyiqnuzckhstkg
wxlnjevbfodajyiqprzcrjstkg
wxlnjqvbhodamyidpuzcrhstkg
wxlnjhvbfodamriqpuzcchstkg
wglnjevbfodamyiqpupfrhstkg
wulnjevdfodamyiqpuzcrhsteg
vxlojevbfodamyiqpuzcrhstsg
wxlnjvvbfodamiiqpuzcrhttkg
wxlnjevbfodabyiqpuzzrhetkg
wxhnjevbfodamyiqpuwcrsstkg
wslzjbvbfodamyiqpuzcrhstkg
rxlnjevbfodhmyiqpupcrhstkg
wxlnjevbfhdamyiqpuvcrhskkg
wxlrjevbxodamyiqpuzcrhstag
wxlsbevbfodammiqpuzcrhstkg
wxlnjzvbfodemyiqpmzcrhstkg
wxlnoevbfodgmyiqpuzbrhstkg
wxlnjefbfodamyinpuzcrhwtkg
bxlnjevbfwdamyiqpuocrhstkg
cxlnjevbjodamyiqpuzcrhslkg
wflnjevbforemyiqpuzcrhstkg
wxlmjeoboodamyiqpuzcrhstkg
wxlnjevbfadaiyiqpuzcrhutkg
wxlnmevbfodamyyqpuzcrjstkg
wxlnjovbfodamyippjzcrhstkg
wxlnjmvbfodamyiqpszcrhsbkg
wxlnjeebfodamyicpuxcrhstkg
wxlnrehbfodamyiqpuzcrhytkg
wxlnjevbfogamyiqwurcrhstkg
wxlujevbnodamyiqpuzcrhstng
wxlnoenofodamyiqpuzcrhstkg
wxsnjevbfsdamyiqsuzcrhstkg
wxlnjevwfodamyiqpuzxrhqtkg
wxlnjevbnodamyiqxulcrhstkg
wxlijetpfodamyiqpuzcrhstkg
wxlnjzvbfidamyiqpuzcrbstkg
wxlnjevefodavyiqpuzcthstkg
wxlnjevbfozamyiqpurcrbstkg
wxlnjfvpfodamyiqpuzcrhntkg
wxlnjevbfvdamyiqvuzcrhqtkg
wilejevbfodamyilpuzcrhstkg
wxlnhevbfodamtiqpuzcrhstke
wxlwjevbfodahyiqppzcrhstkg
wxlnjevbfodamyuqpuzwrrstkg
xxsnjevbfodamyiqpuzcrhstkl
wglnjevbdodamyaqpuzcrhstkg
wxlnjefbwodamyiqpuzcrhsykg
wxwnjevbfodamyiqpuzcrhpckg
wxlnjuvbfidamyiqpuzczhstkg
wxlnzhybfodamyiqpuzcrhstkg
wxunjevufodamyiqpuzcrhspkg
wxunjevbfodcmyiqpuzcrhstcg
wxlnjevbfodhwyiqpuxcrhstkg
wxlnjevtfodasyiqpuzcrhstkb
wxlvjevbfqdamyiqprzcrhstkg
sxlnjevbfodamyiqplzcrhstkq
wxlnlevbfodamyiqpuzcrpstka
wxlnjevbfodaiyiqovzcrhstkg
wxlntevbfodamyiqpuzcrkntkg
wxlnjevbfodsmyiqpuzcrhstir
wxlnnevbfodaoyiqpuzmrhstkg
xxlnjevbfodamyinpnzcrhstkg
wxlnjedefodamyigpuzcrhstkg
wxlnxeabfodamyiqpnzcrhstkg
wxlnxevbfodpmtiqpuzcrhstkg
wxlnjevnfodamyiqpuzcuhqtkg
wxlnjevbfodakyiqluzcrhstmg
wxlnjevbaodamoiqpyzcrhstkg
wwlnjevbfoaajyiqpuzcrhstkg
wxlnjevbfedamyiqpuzcrhsang
wxlwjevbfodamyiqpuzcrmdtkg
wxlnjevbhodamyiqpmzxrhstkg
wxlnjevbfodamyiqpuzzrhwtkj
wxlnjevbfpdvmyiqpuzzrhstkg
wxlnjegcfodamyiqpxzcrhstkg
fxlnjevbfodamyiqpuzcrhstat
wxlnjevbfodcmybqpuzcrkstkg
wxlnjevbfodamiiqpuzrrhstxg
wxvnjevifodamdiqpuzcrhstkg
wxltjevbfodamyiqpuzmrhktkg
wxlnjevbfobaaygqpuzcrhstkg
wmlnjevbfodamyiqpuycrhsukg
wxlnjevboodamyiqpuzcrhuhkg
wxlnjevgfodaqyiqpuzcghstkg
wxlnjevjnodamyiqpuzcrhstke
wclnjevbfodamyiqpuncchstkg
wxlnjevbfndamyxqpuzcshstkg
rxldjevbfodamyiqpuvcrhstkg
wxlnwevbfodamywqpuzrrhstkg
ixlnjevbqodpmyiqpuzcrhstkg
wxlnjlvbfocamyiqpuzgrhstkg
wxlnjevffodamyiqnuzcrhutkg
wxlajevbfodamyiqpuccrhshkg
vwlnjevbfodamyiqpuzcrhstky
wxlajevbfodamyiqpuzcfhstkl
wxlnjevbfodamniqouzcrhstko
wxlnjevbfodamyiqpuzqrhsqka
wxlnjeybfodamyiqpuzclhsnkg
wxbnjlvbfoyamyiqpuzcrhstkg
wxbnjevbfodemyiqpuzcrhstkj
wxlnbefbfodamyiqpkzcrhstkg
wxlnjvvbyodamyitpuzcrhstkg
jxlnjevbfopamyiqpuzprhstkg
wxlnjevbfodaeyiupxzcrhstkg
wnlnjevbfodamyqqpuzcrhstcg
wxlxzuvbfodamyiqpuzcrhstkg
wxlnjevbcodymyiqpuzcrhstke
wxlnjezbfodamynqpuvcrhstkg
wxlnjevbfodamyxlpuzcyhstkg
wxlnjevbffdaiyiqpuzirhstkg
wxlnjevbfodymyiqwuzcrhstfg
wxlnzevbfodscyiqpuzcrhstkg
hxlnjevbfodamyawpuzcrhstkg
welnjevbfodamciqplzcrhstkg
wxlnjeqbfodawyiqpuzkrhstkg
wxlnjelbfodamviqpuzckhstkg
wxlneevjfodamyiqpuzcrhstkd
wxlnjevbfodamyaqpuytrhstkg
wxlnjpvyfodamyiqpuzcshstkg
wxlnjevbfodmbyiqpuzcrhstkp
wxlnjegbfodamdiqpuzcrhstdg
wmlnjevbfodamyiqpuecrhsukg
wxlnjevbfodamyiqpuocrhwtjg
jxfnwevbfodamyiqpuzcrhstkg
wxlnjevffodamyiqpurcrhstkd
wxlnjevbfofamyiqpuzcrhsmkt
wxlnjevbfodmmyiqpuzcrdsttg
axlnjevbfodgmyiqpuzerhstkg
wxtnjevbfodamyifpuwcrhstkg
wxlgjevbfodamyiqpuzrrhvtkg
wxlnjevbfouamyeqfuzcrhstkg
wxlnjevbfmxamyiqpuzcahstkg
wxlnjevffoxamyiqpuecrhstkg
wxlnyevbfodamyiqttzcrhstkg
bxlnjevbfodzmysqpuzcrhstkg
wxlnjevbfodayyiqpuzcrherkg
yxlnjevbfodayyiqpuzcrwstkg
wllnjevbfodambiqpuzurhstkg
wxlnjevbfsdamyiqpuqcrhstkh
wxlcjevbfodamyiqcuzcxhstkg
wxlnjevbfodayticpuzcrhstkg
wxltzevbfodamyiqpzzcrhstkg
wxlnjevbfodamgiqpuzcphstng
wxlnjevbfqdfmziqpuzcrhstkg
wxlnaevbfodamyiqpuzcfustkg
wxlnjevbfodamyxqxuzcrhstdg
wxlnjevkbodamyiqpufcrhstkg
whlnjevbfodauyiqputcrhstkg
wxlnjevbfodamyiephzcrhsnkg
wxlnjevbfodfmoiqpuzcrhstkf
wxlnjevbfodamyiqxuzaxhstkg
wxlnjevtfotamyiqpuzcrhsttg
wxlgjevbfodamyiqpuhcrostkg
dxlnjtvbfodamyiqpuzcshstkg
wxlfjevbfodumyiqppzcrhstkg
wxlnzevbfodamyiqpuzqrhstkx
wflnjevbfodamyiqpurcrhsthg
wxlnjevbfodzfyiqpuzcrjstkg
wxlnjevbfrdamviqpuzmrhstkg
wnlngevmfodamyiqpuzcrhstkg
walzjevbfodamyiqpuzcrhsjkg
wqlnjevbfodamyiqpuzcshslkg
wxlnjevkfodfmyiepuzcrhstkg
wxgnjehbfodamyhqpuzcrhstkg
wxlnjevbfodamyiqfuacrostkg
wxlnjexbfodamyiwpuzcrqstkg
wxlntevafodamyiqpuzcrhsnkg
wxvnjevbfodamyiqpuzcvistkg
mxlnjeebfodamyiqpuzcrhsgkg
wxlnjevyfodamyiqpuzcrhdtkf
wxlnjcvbfodamyicpuzcrhsckg
wxlnjekbfodlmyiqpuzcthstkg
wxlnjvvbfodamyiopuzcrhstqg
wxlnjevbsodamyiqpuhcrhstwg
wxxnjevufodamyiqruzcrhstkg'''

if __name__ == '__main__':
    print(part1(puzzle_input))
    print(part2(puzzle_input))
